import type { CatalogIndex, TopicCatalog, TopicEdge, TopicNode } from './types'

const v = '2026-04-24'

type NodeInput = Omit<TopicNode, 'difficulty' | 'importance'> & {
  difficulty: TopicNode['difficulty'] | number
  importance: TopicNode['importance'] | number
}

function n(input: NodeInput): TopicNode {
  const difficulty = Math.max(1, Math.min(5, Math.round(input.difficulty))) as TopicNode['difficulty']
  const importance = Math.max(1, Math.min(5, Math.round(input.importance))) as TopicNode['importance']
  return { ...input, difficulty, importance }
}

function e(input: TopicEdge): TopicEdge {
  return input
}

/**
 * 设计原则（第一性原理）
 * - 以“对象-性质-运算-结构-方法-应用”为主线拆分内容点
 * - 以“先修依赖/共现关系/推导关系/相似迁移”为边，支持测量学的题型蓝图与能力指标
 * - 节点粒度：定义/定理/方法/典型题型/易错点 5 类混合，以便真实覆盖考试命题
 */
export const hmCatalog: TopicCatalog = {
  version: v,
  nodes: [
    // =========================
    // 函数与极限
    // =========================
    n({
      id: 'LIM_ROOT',
      label: '函数与极限（章）',
      chapter: '函数与极限',
      difficulty: 1,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['章根'],
    }),
    n({
      id: 'LIM_001',
      label: '函数概念：定义域/值域/对应法则',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 1,
      importance: 4,
      cognitive: ['记忆', '理解'],
      tags: ['定义', '基础'],
      alias: ['映射', '函数三要素'],
    }),
    n({
      id: 'LIM_002',
      label: '常见初等函数与图像（幂/指/对/三角/反三角）',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 1,
      importance: 4,
      cognitive: ['记忆', '理解'],
      tags: ['图像', '基础'],
    }),
    n({
      id: 'LIM_003',
      label: '函数性质：奇偶性/周期性/单调性/有界性',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 2,
      importance: 4,
      cognitive: ['理解', '应用'],
      tags: ['性质', '判定'],
    }),
    n({
      id: 'LIM_004',
      label: '复合函数与反函数：可逆条件/求反函数',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 2,
      importance: 3,
      cognitive: ['理解', '应用', '分析'],
      tags: ['方法'],
    }),
    n({
      id: 'LIM_005',
      label: '初等变换：平移/伸缩/对称（图像法）',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 1,
      importance: 3,
      cognitive: ['理解', '应用'],
      tags: ['图像', '技巧'],
    }),
    n({
      id: 'LIM_010',
      label: '数列极限：\u03b5-N 定义与性质',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['理解', '分析'],
      tags: ['定义', '严谨'],
      alias: ['ε-N'],
    }),
    n({
      id: 'LIM_011',
      label: '函数极限：\u03b5-\u03b4 定义与等价无穷小',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 3,
      importance: 5,
      cognitive: ['理解', '应用', '分析'],
      tags: ['定义', '等价无穷小'],
      alias: ['ε-δ', '无穷小'],
    }),
    n({
      id: 'LIM_012',
      label: '极限四则运算与夹逼定理',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 2,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['定理', '求极限'],
    }),
    n({
      id: 'LIM_013',
      label: '单调有界定理（数列）与收敛判别',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['理解', '分析'],
      tags: ['定理', '判别'],
    }),
    n({
      id: 'LIM_014',
      label: '重要极限：sinx/x、(1+1/x)^x 等',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 2,
      importance: 5,
      cognitive: ['记忆', '应用'],
      tags: ['公式', '常考'],
    }),
    n({
      id: 'LIM_015',
      label: '无穷小比较：同阶/高阶/等价',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 2,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['技巧', '常考'],
    }),
    n({
      id: 'LIM_016',
      label: '洛必达法则：0/0、∞/∞ 及变形',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 3,
      importance: 5,
      cognitive: ['应用', '分析'],
      tags: ['方法', '求极限'],
    }),
    n({
      id: 'LIM_017',
      label: '连续性：间断点分类与连续运算',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 2,
      importance: 4,
      cognitive: ['理解', '应用', '分析'],
      tags: ['概念', '分类'],
    }),
    n({
      id: 'LIM_018',
      label: '闭区间连续性质：最大最小值定理/介值定理',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 2,
      importance: 4,
      cognitive: ['理解', '应用'],
      tags: ['定理', '证明'],
    }),
    n({
      id: 'LIM_019',
      label: '一致连续（了解）与反例构造思路',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 4,
      importance: 2,
      cognitive: ['理解', '分析'],
      tags: ['拓展', '反例'],
    }),
    n({
      id: 'LIM_020',
      label: '无穷大/无穷小与渐近线（水平/竖直/斜）',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['理解', '应用', '分析'],
      tags: ['渐近线', '常考'],
    }),
    n({
      id: 'LIM_021',
      label: '极限求法：有理化/通分/因式分解/配凑',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 2,
      importance: 5,
      cognitive: ['应用'],
      tags: ['技巧', '常考'],
    }),
    n({
      id: 'LIM_022',
      label: '极限求法：变量代换（x=1/t, t=tan(x/2) 等）',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['代换', '技巧'],
    }),
    n({
      id: 'LIM_023',
      label: '等价无穷小表与常用替换（sinx~x, 1-cosx~x^2/2 等）',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 2,
      importance: 5,
      cognitive: ['记忆', '应用'],
      tags: ['等价无穷小', '常考'],
    }),
    n({
      id: 'LIM_024',
      label: '连续函数的零点定理与方程根的存在性（介值法）',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['证明', '存在性'],
    }),
    n({
      id: 'LIM_025',
      label: '典型题型：分段函数在断点处连续/可导参数求解',
      chapter: '函数与极限',
      parentId: 'LIM_ROOT',
      difficulty: 4,
      importance: 5,
      cognitive: ['分析', '综合', '评价'],
      tags: ['分段', '参数', '常考'],
    }),

    // =========================
    // 一元微分学
    // =========================
    n({
      id: 'DIFF1_ROOT',
      label: '一元微分学（章）',
      chapter: '一元微分学',
      difficulty: 1,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['章根'],
    }),
    n({
      id: 'DIFF1_001',
      label: '导数定义：增量比/几何意义/物理意义',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 2,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['定义', '几何'],
    }),
    n({
      id: 'DIFF1_002',
      label: '可导与连续关系：可导必连续（反例）',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 2,
      importance: 4,
      cognitive: ['理解', '分析'],
      tags: ['性质', '反例'],
    }),
    n({
      id: 'DIFF1_003',
      label: '基本求导公式与四则/复合求导（链式法则）',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 2,
      importance: 5,
      cognitive: ['记忆', '应用'],
      tags: ['公式', '方法'],
    }),
    n({
      id: 'DIFF1_004',
      label: '隐函数求导与参数方程求导',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 3,
      importance: 5,
      cognitive: ['应用', '分析'],
      tags: ['方法', '常考'],
    }),
    n({
      id: 'DIFF1_005',
      label: '高阶导数与 Leibniz 公式（乘积 n 阶）',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '分析', '综合'],
      tags: ['方法', '技巧'],
    }),
    n({
      id: 'DIFF1_006',
      label: '微分：dy 及线性近似、误差估计',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['理解', '应用'],
      tags: ['应用', '近似'],
    }),
    n({
      id: 'DIFF1_010',
      label: '中值定理：罗尔/拉格朗日/柯西',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 5,
      cognitive: ['理解', '应用', '分析'],
      tags: ['定理', '证明', '常考'],
    }),
    n({
      id: 'DIFF1_011',
      label: '泰勒公式：Peano/拉格朗日余项、展开技巧',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 5,
      cognitive: ['应用', '分析', '综合'],
      tags: ['定理', '展开', '常考'],
      alias: ['Taylor', '麦克劳林'],
    }),
    n({
      id: 'DIFF1_012',
      label: '洛必达与泰勒的选择：判型与策略',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['分析', '综合', '评价'],
      tags: ['策略', '对比'],
    }),
    n({
      id: 'DIFF1_013',
      label: '单调性与极值：一阶/二阶判别',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 3,
      importance: 5,
      cognitive: ['应用', '分析'],
      tags: ['应用', '常考'],
    }),
    n({
      id: 'DIFF1_014',
      label: '曲线凹凸与拐点：二阶导数、图像分析',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['图像', '应用'],
    }),
    n({
      id: 'DIFF1_015',
      label: '最值问题（应用题）：建模-求导-检验',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '综合', '评价'],
      tags: ['建模', '应用题'],
    }),
    n({
      id: 'DIFF1_016',
      label: '不等式证明：中值定理/泰勒/单调性方法',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['分析', '综合', '评价'],
      tags: ['证明', '综合题'],
    }),
    n({
      id: 'DIFF1_017',
      label: '曲率与曲率半径（常见题型）',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 3,
      cognitive: ['应用', '分析'],
      tags: ['几何应用'],
    }),
    n({
      id: 'DIFF1_018',
      label: '函数作图：渐近线/驻点/凹凸/间断综合',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['综合', '评价'],
      tags: ['综合', '常考'],
    }),
    n({
      id: 'DIFF1_019',
      label: '反函数求导：y=f^{-1}(x) 的导数公式与应用',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['理解', '应用'],
      tags: ['方法'],
    }),
    n({
      id: 'DIFF1_020',
      label: '对数求导：幂指复合形式（y=u(x)^{v(x)}）',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['技巧', '常考'],
    }),
    n({
      id: 'DIFF1_021',
      label: '相关变化率：建模 + 隐函数求导 + 单位一致性',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 3,
      cognitive: ['综合', '评价'],
      tags: ['建模', '应用题'],
    }),
    n({
      id: 'DIFF1_022',
      label: '微分中值定理常用推论：单调/不等式/零点个数',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['分析', '综合'],
      tags: ['推论', '证明'],
    }),
    n({
      id: 'DIFF1_023',
      label: '常考极限：利用泰勒与等价无穷小的“阶”比较',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['分析', '综合'],
      tags: ['求极限', '策略'],
    }),
    n({
      id: 'DIFF1_024',
      label: 'Newton 迭代（了解）：切线法与收敛直观',
      chapter: '一元微分学',
      parentId: 'DIFF1_ROOT',
      difficulty: 4,
      importance: 2,
      cognitive: ['理解', '应用'],
      tags: ['拓展'],
    }),

    // =========================
    // 一元积分学
    // =========================
    n({
      id: 'INT1_ROOT',
      label: '一元积分学（章）',
      chapter: '一元积分学',
      difficulty: 1,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['章根'],
    }),
    n({
      id: 'INT1_001',
      label: '不定积分：原函数概念与基本积分公式',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 2,
      importance: 5,
      cognitive: ['记忆', '应用'],
      tags: ['定义', '公式'],
    }),
    n({
      id: 'INT1_002',
      label: '换元积分法：第一类/第二类',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 3,
      importance: 5,
      cognitive: ['应用', '分析'],
      tags: ['方法', '常考'],
    }),
    n({
      id: 'INT1_003',
      label: '分部积分法：循环/表格法/构造技巧',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 4,
      importance: 5,
      cognitive: ['应用', '分析', '综合'],
      tags: ['方法', '常考'],
    }),
    n({
      id: 'INT1_004',
      label: '有理函数积分：部分分式分解',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['技巧'],
    }),
    n({
      id: 'INT1_005',
      label: '三角积分与万能代换（tan(x/2)）',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['技巧', '常考'],
    }),
    n({
      id: 'INT1_006',
      label: '定积分定义：Riemann 和/可积判别要点',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['理解', '分析'],
      tags: ['定义', '严谨'],
    }),
    n({
      id: 'INT1_007',
      label: '牛顿-莱布尼茨公式：基本定理与变上限积分',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 3,
      importance: 5,
      cognitive: ['理解', '应用', '分析'],
      tags: ['定理', '常考'],
    }),
    n({
      id: 'INT1_008',
      label: '积分性质：线性/保序/估值与不等式',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['分析', '综合'],
      tags: ['性质', '不等式'],
    }),
    n({
      id: 'INT1_009',
      label: '反常积分：判别（比较/极限/积分判别）',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['分析', '综合'],
      tags: ['判别', '常考'],
    }),
    n({
      id: 'INT1_010',
      label: '面积：直角坐标/极坐标/参数方程',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '综合'],
      tags: ['几何应用'],
    }),
    n({
      id: 'INT1_011',
      label: '体积：旋转体（盘/壳）与截面法',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '综合'],
      tags: ['几何应用'],
    }),
    n({
      id: 'INT1_012',
      label: '弧长与曲线积分（平面曲线）',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 5,
      importance: 3,
      cognitive: ['应用', '分析'],
      tags: ['几何应用'],
    }),
    n({
      id: 'INT1_013',
      label: '物理应用：功/质心/转动惯量/流体压力',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 4,
      importance: 3,
      cognitive: ['综合', '评价'],
      tags: ['建模', '应用题'],
    }),
    n({
      id: 'INT1_014',
      label: '定积分性质常考：区间可加/变量替换/奇偶对称/周期',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 4,
      importance: 5,
      cognitive: ['应用', '分析'],
      tags: ['性质', '常考'],
    }),
    n({
      id: 'INT1_015',
      label: '定积分计算技巧：凑微分/拆分/换元/分部综合',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 4,
      importance: 5,
      cognitive: ['分析', '综合'],
      tags: ['技巧', '常考'],
    }),
    n({
      id: 'INT1_016',
      label: '积分不等式：Jensen/切线法/积分均值定理（常见套路）',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 5,
      importance: 3,
      cognitive: ['分析', '综合', '评价'],
      tags: ['不等式', '证明'],
    }),
    n({
      id: 'INT1_017',
      label: '典型题型：含参定积分求值/求导（积分号下求导）',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['综合', '评价'],
      tags: ['含参', '常考'],
    }),
    n({
      id: 'INT1_018',
      label: '反常积分与级数类比：p-积分、比较判别',
      chapter: '一元积分学',
      parentId: 'INT1_ROOT',
      difficulty: 5,
      importance: 3,
      cognitive: ['分析'],
      tags: ['类比', '判别'],
    }),

    // =========================
    // 常微分方程
    // =========================
    n({
      id: 'ODE_ROOT',
      label: '常微分方程（章）',
      chapter: '常微分方程',
      difficulty: 2,
      importance: 4,
      cognitive: ['理解', '应用'],
      tags: ['章根'],
    }),
    n({
      id: 'ODE_001',
      label: '微分方程基本概念：阶/解/初值问题',
      chapter: '常微分方程',
      parentId: 'ODE_ROOT',
      difficulty: 2,
      importance: 3,
      cognitive: ['理解'],
      tags: ['概念'],
    }),
    n({
      id: 'ODE_002',
      label: '可分离变量方程：变量分离与积分',
      chapter: '常微分方程',
      parentId: 'ODE_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['应用'],
      tags: ['方法', '常考'],
    }),
    n({
      id: 'ODE_003',
      label: '一阶线性方程：常数变易法/积分因子',
      chapter: '常微分方程',
      parentId: 'ODE_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['方法', '常考'],
    }),
    n({
      id: 'ODE_004',
      label: '齐次/伯努利/全微分方程（识别与套路）',
      chapter: '常微分方程',
      parentId: 'ODE_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['分析', '综合'],
      tags: ['判型', '套路'],
    }),
    n({
      id: 'ODE_005',
      label: '二阶常系数线性方程：特征方程与通解',
      chapter: '常微分方程',
      parentId: 'ODE_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['方法', '常考'],
    }),
    n({
      id: 'ODE_006',
      label: '二阶非齐次：待定系数/变参数法（了解）',
      chapter: '常微分方程',
      parentId: 'ODE_ROOT',
      difficulty: 5,
      importance: 3,
      cognitive: ['应用', '综合'],
      tags: ['方法'],
    }),
    n({
      id: 'ODE_007',
      label: '应用建模：增长/衰减/混合/振动（基本模型）',
      chapter: '常微分方程',
      parentId: 'ODE_ROOT',
      difficulty: 4,
      importance: 3,
      cognitive: ['综合', '评价'],
      tags: ['建模'],
    }),
    n({
      id: 'ODE_008',
      label: '高阶降阶：已知一个解/方程缺变量（了解）',
      chapter: '常微分方程',
      parentId: 'ODE_ROOT',
      difficulty: 5,
      importance: 2,
      cognitive: ['分析'],
      tags: ['拓展'],
    }),

    // =========================
    // 向量代数与空间解析几何
    // =========================
    n({
      id: 'VEC_ROOT',
      label: '向量代数与空间解析几何（章）',
      chapter: '向量代数与空间解析几何',
      difficulty: 2,
      importance: 3,
      cognitive: ['理解', '应用'],
      tags: ['章根'],
    }),
    n({
      id: 'VEC_001',
      label: '向量运算：加减/数乘/线性表示',
      chapter: '向量代数与空间解析几何',
      parentId: 'VEC_ROOT',
      difficulty: 2,
      importance: 3,
      cognitive: ['理解', '应用'],
      tags: ['基础'],
    }),
    n({
      id: 'VEC_002',
      label: '数量积与夹角：正交/投影/距离',
      chapter: '向量代数与空间解析几何',
      parentId: 'VEC_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['应用'],
      tags: ['几何'],
    }),
    n({
      id: 'VEC_003',
      label: '向量积与混合积：面积/体积/共面判别',
      chapter: '向量代数与空间解析几何',
      parentId: 'VEC_ROOT',
      difficulty: 4,
      importance: 3,
      cognitive: ['应用', '分析'],
      tags: ['判别'],
    }),
    n({
      id: 'VEC_004',
      label: '平面与直线：点法式/一般式/夹角与距离',
      chapter: '向量代数与空间解析几何',
      parentId: 'VEC_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['方程', '几何'],
    }),
    n({
      id: 'VEC_005',
      label: '二次曲面：球/椭球/抛物面/双曲面（识别）',
      chapter: '向量代数与空间解析几何',
      parentId: 'VEC_ROOT',
      difficulty: 4,
      importance: 2,
      cognitive: ['理解', '应用'],
      tags: ['识别'],
    }),
    n({
      id: 'VEC_006',
      label: '空间曲线参数方程：切向量/法向量/曲率（衔接多元）',
      chapter: '向量代数与空间解析几何',
      parentId: 'VEC_ROOT',
      difficulty: 5,
      importance: 2,
      cognitive: ['理解', '应用'],
      tags: ['拓展', '衔接'],
    }),

    // =========================
    // 多元函数微分学
    // =========================
    n({
      id: 'DIFFM_ROOT',
      label: '多元函数微分学（章）',
      chapter: '多元函数微分学',
      difficulty: 2,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['章根'],
    }),
    n({
      id: 'DIFFM_001',
      label: '二元/多元函数：图形与水平集（等值线/等值面）',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 2,
      importance: 3,
      cognitive: ['理解'],
      tags: ['几何直观'],
    }),
    n({
      id: 'DIFFM_002',
      label: '极限与连续（多元）：路径法与反例',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合'],
      tags: ['反例', '常考'],
    }),
    n({
      id: 'DIFFM_003',
      label: '偏导数与全微分：可微判别与充分条件',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['理解', '分析', '综合'],
      tags: ['判别', '常考'],
    }),
    n({
      id: 'DIFFM_004',
      label: '方向导数与梯度：最速下降方向与几何意义',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['理解', '应用', '分析'],
      tags: ['几何', '应用'],
    }),
    n({
      id: 'DIFFM_005',
      label: '复合函数求导：链式法则（多元）',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['方法'],
    }),
    n({
      id: 'DIFFM_006',
      label: '隐函数定理与方程组求导（雅可比）',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['分析', '综合'],
      tags: ['方法', '雅可比'],
    }),
    n({
      id: 'DIFFM_007',
      label: '二阶偏导与混合偏导：Clairaut 定理条件',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 4,
      importance: 3,
      cognitive: ['理解', '应用'],
      tags: ['性质'],
    }),
    n({
      id: 'DIFFM_008',
      label: '二元泰勒公式与二次型判别（Hessian）',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合', '评价'],
      tags: ['极值', '常考'],
    }),
    n({
      id: 'DIFFM_009',
      label: '无条件极值：驻点/鞍点/最值判别',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合'],
      tags: ['极值', '常考'],
    }),
    n({
      id: 'DIFFM_010',
      label: '条件极值：拉格朗日乘子法（约束）',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['综合', '评价'],
      tags: ['优化', '常考'],
    }),
    n({
      id: 'DIFFM_011',
      label: '典型题型：二元极限存在性（路径法/极坐标法）',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合'],
      tags: ['题型', '常考'],
    }),
    n({
      id: 'DIFFM_012',
      label: '典型题型：偏导存在但不可微/不可连续的构造',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['分析', '综合', '评价'],
      tags: ['反例', '常考'],
    }),
    n({
      id: 'DIFFM_013',
      label: '隐函数求偏导：F(x,y,z)=0 与链式法则联用',
      chapter: '多元函数微分学',
      parentId: 'DIFFM_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['应用', '综合'],
      tags: ['题型', '常考'],
    }),

    // =========================
    // 多元函数积分学
    // =========================
    n({
      id: 'INTM_ROOT',
      label: '多元函数积分学（章）',
      chapter: '多元函数积分学',
      difficulty: 3,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['章根'],
    }),
    n({
      id: 'INTM_001',
      label: '二重积分：直角坐标与积分区域（I/II 型）',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 4,
      importance: 5,
      cognitive: ['应用', '分析'],
      tags: ['区域', '常考'],
    }),
    n({
      id: 'INTM_002',
      label: '二重积分换元：极坐标/雅可比（平面）',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合'],
      tags: ['换元', '雅可比', '常考'],
    }),
    n({
      id: 'INTM_003',
      label: '三重积分：空间区域与柱/球坐标',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['应用', '综合'],
      tags: ['区域', '换元'],
    }),
    n({
      id: 'INTM_004',
      label: '质量/质心/转动惯量：重积分建模',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 3,
      cognitive: ['综合', '评价'],
      tags: ['建模'],
    }),
    n({
      id: 'INTM_005',
      label: '曲线积分（第一型）：弧长/质量/功（平面/空间）',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['应用', '综合'],
      tags: ['曲线积分'],
    }),
    n({
      id: 'INTM_006',
      label: '曲线积分（第二型）：Pdx+Qdy+Rdz 与路径',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['分析', '综合'],
      tags: ['向量场', '常考'],
    }),
    n({
      id: 'INTM_007',
      label: '格林公式：平面区域的环量与通量',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合', '评价'],
      tags: ['定理', '常考'],
    }),
    n({
      id: 'INTM_008',
      label: '曲面积分（第一型）：\u222f_S f dS 与参数化',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['应用', '综合'],
      tags: ['曲面积分'],
    }),
    n({
      id: 'INTM_009',
      label: '曲面积分（第二型）：通量 \u222f_S P dy dz + ...',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['分析', '综合'],
      tags: ['通量', '向量场'],
    }),
    n({
      id: 'INTM_010',
      label: '高斯公式（散度定理）：体积分↔通量',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合'],
      tags: ['定理', '常考'],
    }),
    n({
      id: 'INTM_011',
      label: '斯托克斯公式：曲线积分↔曲面积分',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['分析', '综合'],
      tags: ['定理'],
    }),
    n({
      id: 'INTM_012',
      label: '向量分析量：旋度/散度/保守场与势函数',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合'],
      tags: ['向量场', '常考'],
    }),
    n({
      id: 'INTM_013',
      label: '改变积分次序：区域分割与画图（考试高频）',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合', '评价'],
      tags: ['技巧', '常考'],
    }),
    n({
      id: 'INTM_014',
      label: '对称性：奇偶对称/轮换对称简化二重三重积分',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['应用', '分析'],
      tags: ['技巧'],
    }),
    n({
      id: 'INTM_015',
      label: '二重积分几何意义：体积/面积/概率密度',
      chapter: '多元函数积分学',
      parentId: 'INTM_ROOT',
      difficulty: 4,
      importance: 3,
      cognitive: ['理解', '应用'],
      tags: ['意义'],
    }),

    // =========================
    // 无穷级数
    // =========================
    n({
      id: 'SER_ROOT',
      label: '无穷级数（章）',
      chapter: '无穷级数',
      difficulty: 3,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['章根'],
    }),
    n({
      id: 'SER_001',
      label: '数项级数：收敛/发散与必要条件',
      chapter: '无穷级数',
      parentId: 'SER_ROOT',
      difficulty: 3,
      importance: 4,
      cognitive: ['理解', '分析'],
      tags: ['概念'],
    }),
    n({
      id: 'SER_002',
      label: '正项级数判别：比较/比值/根值/积分',
      chapter: '无穷级数',
      parentId: 'SER_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合', '评价'],
      tags: ['判别', '常考'],
    }),
    n({
      id: 'SER_003',
      label: '交错级数：莱布尼茨判别与误差估计',
      chapter: '无穷级数',
      parentId: 'SER_ROOT',
      difficulty: 4,
      importance: 4,
      cognitive: ['分析', '应用'],
      tags: ['判别'],
    }),
    n({
      id: 'SER_004',
      label: '任意项级数：绝对/条件收敛、Dirichlet/Abel',
      chapter: '无穷级数',
      parentId: 'SER_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['分析', '综合'],
      tags: ['判别'],
    }),
    n({
      id: 'SER_005',
      label: '幂级数：收敛半径与收敛域（比值法）',
      chapter: '无穷级数',
      parentId: 'SER_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['分析', '综合'],
      tags: ['幂级数', '常考'],
    }),
    n({
      id: 'SER_006',
      label: '幂级数运算：逐项求导/积分、函数展开',
      chapter: '无穷级数',
      parentId: 'SER_ROOT',
      difficulty: 5,
      importance: 5,
      cognitive: ['综合', '评价'],
      tags: ['展开', '常考'],
    }),
    n({
      id: 'SER_007',
      label: '常用函数展开：e^x、sinx、ln(1+x)、(1+x)^a',
      chapter: '无穷级数',
      parentId: 'SER_ROOT',
      difficulty: 4,
      importance: 5,
      cognitive: ['记忆', '应用', '分析'],
      tags: ['展开', '公式', '常考'],
    }),
    n({
      id: 'SER_008',
      label: '傅里叶级数（了解）：展开系数与奇偶延拓',
      chapter: '无穷级数',
      parentId: 'SER_ROOT',
      difficulty: 5,
      importance: 2,
      cognitive: ['理解', '应用'],
      tags: ['拓展'],
    }),
    n({
      id: 'SER_009',
      label: '幂级数求和：由已知展开变形/积分/求导得到',
      chapter: '无穷级数',
      parentId: 'SER_ROOT',
      difficulty: 5,
      importance: 4,
      cognitive: ['综合', '评价'],
      tags: ['求和', '常考'],
    }),
    n({
      id: 'SER_010',
      label: '级数与函数极限/积分：交换次序的条件（了解）',
      chapter: '无穷级数',
      parentId: 'SER_ROOT',
      difficulty: 5,
      importance: 2,
      cognitive: ['理解', '分析'],
      tags: ['拓展'],
    }),

    // =========================
    // 第一性原理：最底层元命题（非章节标题，用于语义锚定与跨域降维）
    // =========================
    n({
      id: 'FP_ROOT',
      label: '第一性原理与元结构（层）',
      chapter: '第一性原理与元结构',
      difficulty: 1,
      importance: 5,
      cognitive: ['理解', '分析'],
      tags: ['章根'],
    }),
    n({
      id: 'FP_C01',
      label: '完备序：上确界刻画「无空隙」的实数轴',
      chapter: '第一性原理与元结构',
      parentId: 'FP_ROOT',
      axes: ['完备与序'],
      difficulty: 5,
      importance: 4,
      cognitive: ['理解'],
      tags: ['元概念', '完备'],
    }),
    n({
      id: 'FP_E01',
      label: 'ε-δ 语言：把「要多接近」翻译成不等式控制',
      chapter: '第一性原理与元结构',
      parentId: 'FP_ROOT',
      axes: ['ε-δ与逼近'],
      difficulty: 4,
      importance: 5,
      cognitive: ['理解', '分析'],
      tags: ['元概念', '逼近'],
    }),
    n({
      id: 'FP_L01',
      label: '局部线性：可微 ⇒ 切空间上的最佳仿射逼近',
      chapter: '第一性原理与元结构',
      parentId: 'FP_ROOT',
      axes: ['局部线性'],
      difficulty: 4,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['元概念', '切空间'],
    }),
    n({
      id: 'FP_M01',
      label: '中值信息：导数在区间内「插值」函数增量',
      chapter: '第一性原理与元结构',
      parentId: 'FP_ROOT',
      axes: ['中值与凸性'],
      difficulty: 4,
      importance: 5,
      cognitive: ['理解', '分析'],
      tags: ['元概念', '插值'],
    }),
    n({
      id: 'FP_T01',
      label: 'Taylor：用多项式在一点附近匹配各阶导数信息',
      chapter: '第一性原理与元结构',
      parentId: 'FP_ROOT',
      axes: ['Taylor与多项式'],
      difficulty: 5,
      importance: 5,
      cognitive: ['理解', '分析'],
      tags: ['元概念', '局部逼近'],
    }),
    n({
      id: 'FP_I01',
      label: '累积算子：分割求和 + 极限 ⇒ 积分',
      chapter: '第一性原理与元结构',
      parentId: 'FP_ROOT',
      axes: ['累积与分割'],
      difficulty: 4,
      importance: 5,
      cognitive: ['理解', '应用'],
      tags: ['元概念', '求和极限'],
    }),
    n({
      id: 'FP_J01',
      label: '换元本质：坐标变换下体积元按雅可比伸缩',
      chapter: '第一性原理与元结构',
      parentId: 'FP_ROOT',
      axes: ['换元与雅可比'],
      difficulty: 5,
      importance: 5,
      cognitive: ['理解', '分析'],
      tags: ['元概念', '体积元'],
    }),
    n({
      id: 'FP_V01',
      label: '场论视角：通量/环量把微分与几何定向绑定',
      chapter: '第一性原理与元结构',
      parentId: 'FP_ROOT',
      axes: ['场线通量环量'],
      difficulty: 5,
      importance: 4,
      cognitive: ['理解', '分析'],
      tags: ['元概念', '定向'],
    }),
    n({
      id: 'FP_S01',
      label: '收敛：部分和/余项是否可被「尾巴」任意压小',
      chapter: '第一性原理与元结构',
      parentId: 'FP_ROOT',
      axes: ['收敛与紧性'],
      difficulty: 4,
      importance: 5,
      cognitive: ['理解', '分析'],
      tags: ['元概念', '尾巴'],
    }),
    n({
      id: 'FP_B01',
      label: '对称/凸性：把「比较大小」变成结构不等式',
      chapter: '第一性原理与元结构',
      parentId: 'FP_ROOT',
      axes: ['对称与估计'],
      difficulty: 4,
      importance: 4,
      cognitive: ['理解', '分析'],
      tags: ['元概念', '不等式'],
    }),
  ],
  edges: [
    // 函数与极限内部
    e({ source: 'LIM_001', target: 'LIM_003', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'LIM_011', target: 'LIM_012', type: 'PREREQ', weight: 0.9 }),
    e({ source: 'LIM_014', target: 'LIM_016', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'LIM_015', target: 'LIM_016', type: 'PREREQ', weight: 0.8 }),
    e({ source: 'LIM_017', target: 'LIM_018', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'LIM_012', target: 'LIM_017', type: 'DERIVES', weight: 0.6 }),
    e({ source: 'LIM_012', target: 'LIM_021', type: 'CO_OCCUR', weight: 0.4 }),
    e({ source: 'LIM_023', target: 'LIM_015', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'LIM_020', target: 'DIFF1_018', type: 'CO_OCCUR', weight: 0.5 }),
    e({ source: 'LIM_025', target: 'DIFF1_002', type: 'CO_OCCUR', weight: 0.6 }),

    // 极限 -> 导数
    e({ source: 'LIM_011', target: 'DIFF1_001', type: 'PREREQ', weight: 1 }),
    e({ source: 'LIM_017', target: 'DIFF1_002', type: 'PREREQ', weight: 0.8 }),
    e({ source: 'LIM_016', target: 'DIFF1_012', type: 'CO_OCCUR', weight: 0.6 }),
    e({ source: 'DIFF1_011', target: 'LIM_014', type: 'CO_OCCUR', weight: 0.5 }),

    // 导数内部
    e({ source: 'DIFF1_001', target: 'DIFF1_003', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'DIFF1_003', target: 'DIFF1_004', type: 'PREREQ', weight: 0.8 }),
    e({ source: 'DIFF1_003', target: 'DIFF1_005', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'DIFF1_003', target: 'DIFF1_010', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'DIFF1_010', target: 'DIFF1_013', type: 'PREREQ', weight: 0.8 }),
    e({ source: 'DIFF1_014', target: 'DIFF1_018', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'DIFF1_013', target: 'DIFF1_015', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'DIFF1_011', target: 'DIFF1_016', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'DIFF1_010', target: 'DIFF1_016', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'DIFF1_004', target: 'DIFF1_021', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'DIFF1_010', target: 'DIFF1_022', type: 'DERIVES', weight: 0.7 }),
    e({ source: 'DIFF1_011', target: 'DIFF1_023', type: 'DERIVES', weight: 0.7 }),

    // 导数 -> 积分
    e({ source: 'DIFF1_003', target: 'INT1_001', type: 'SIMILAR', weight: 0.5 }),
    e({ source: 'DIFF1_010', target: 'INT1_007', type: 'DERIVES', weight: 0.9 }),
    e({ source: 'INT1_007', target: 'INT1_010', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'INT1_001', target: 'INT1_002', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'INT1_001', target: 'INT1_003', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'INT1_006', target: 'INT1_007', type: 'PREREQ', weight: 0.8 }),
    e({ source: 'INT1_007', target: 'INT1_009', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'INT1_007', target: 'INT1_017', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'INT1_014', target: 'INT1_015', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'INT1_009', target: 'INT1_018', type: 'SIMILAR', weight: 0.6 }),

    // 积分 -> 微分方程/级数
    e({ source: 'INT1_002', target: 'ODE_002', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'INT1_007', target: 'ODE_003', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'DIFF1_011', target: 'SER_007', type: 'SIMILAR', weight: 0.7 }),
    e({ source: 'SER_007', target: 'SER_006', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'SER_005', target: 'SER_006', type: 'PREREQ', weight: 0.8 }),
    e({ source: 'SER_006', target: 'SER_009', type: 'PREREQ', weight: 0.7 }),

    // 向量/空间 -> 多元/积分
    e({ source: 'VEC_002', target: 'DIFFM_004', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'VEC_004', target: 'INTM_003', type: 'PREREQ', weight: 0.5 }),
    e({ source: 'VEC_006', target: 'INTM_008', type: 'CO_OCCUR', weight: 0.4 }),

    // 多元微分内部与到重积分
    e({ source: 'DIFFM_002', target: 'DIFFM_003', type: 'PREREQ', weight: 0.8 }),
    e({ source: 'DIFFM_003', target: 'DIFFM_004', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'DIFFM_003', target: 'DIFFM_008', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'DIFFM_009', target: 'DIFFM_010', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'DIFFM_003', target: 'INTM_001', type: 'PREREQ', weight: 0.7 }),
    e({ source: 'INTM_001', target: 'INTM_002', type: 'PREREQ', weight: 0.8 }),
    e({ source: 'INTM_002', target: 'INTM_003', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'INTM_006', target: 'INTM_007', type: 'PREREQ', weight: 0.8 }),
    e({ source: 'INTM_007', target: 'INTM_010', type: 'PREREQ', weight: 0.6 }),
    e({ source: 'INTM_011', target: 'INTM_012', type: 'CO_OCCUR', weight: 0.5 }),
    e({ source: 'INTM_001', target: 'INTM_013', type: 'PREREQ', weight: 0.8 }),
    e({ source: 'INTM_013', target: 'INTM_014', type: 'CO_OCCUR', weight: 0.5 }),

    // —— 元命题 → 教材底层考点（语义锚定）——
    e({ source: 'FP_C01', target: 'LIM_013', type: 'DERIVES', weight: 0.85 }),
    e({ source: 'FP_E01', target: 'LIM_011', type: 'DERIVES', weight: 0.95 }),
    e({ source: 'FP_E01', target: 'LIM_010', type: 'DERIVES', weight: 0.75 }),
    e({ source: 'FP_L01', target: 'DIFF1_001', type: 'DERIVES', weight: 0.95 }),
    e({ source: 'FP_L01', target: 'DIFFM_003', type: 'DERIVES', weight: 0.85 }),
    e({ source: 'FP_M01', target: 'DIFF1_010', type: 'DERIVES', weight: 0.9 }),
    e({ source: 'FP_T01', target: 'DIFF1_011', type: 'DERIVES', weight: 0.95 }),
    e({ source: 'FP_T01', target: 'SER_006', type: 'DERIVES', weight: 0.85 }),
    e({ source: 'FP_I01', target: 'INT1_006', type: 'DERIVES', weight: 0.85 }),
    e({ source: 'FP_I01', target: 'INT1_007', type: 'DERIVES', weight: 0.95 }),
    e({ source: 'FP_J01', target: 'INT1_002', type: 'SIMILAR', weight: 0.7 }),
    e({ source: 'FP_J01', target: 'INTM_002', type: 'DERIVES', weight: 0.9 }),
    e({ source: 'FP_J01', target: 'DIFFM_006', type: 'SIMILAR', weight: 0.75 }),
    e({ source: 'FP_V01', target: 'INTM_006', type: 'DERIVES', weight: 0.85 }),
    e({ source: 'FP_V01', target: 'INTM_007', type: 'DERIVES', weight: 0.85 }),
    e({ source: 'FP_S01', target: 'SER_001', type: 'DERIVES', weight: 0.85 }),
    e({ source: 'FP_S01', target: 'INT1_009', type: 'SIMILAR', weight: 0.75 }),
    e({ source: 'FP_B01', target: 'INT1_008', type: 'SIMILAR', weight: 0.7 }),

    // —— 跨章「最底层」语义边（同一元轴上的操作迁移）——
    e({ source: 'LIM_011', target: 'DIFFM_002', type: 'SIMILAR', weight: 0.65 }),
    e({ source: 'LIM_015', target: 'DIFF1_011', type: 'SIMILAR', weight: 0.7 }),
    e({ source: 'DIFF1_011', target: 'SER_007', type: 'DERIVES', weight: 0.75 }),
    e({ source: 'DIFF1_003', target: 'DIFFM_005', type: 'SIMILAR', weight: 0.8 }),
    e({ source: 'INT1_007', target: 'DIFFM_006', type: 'SIMILAR', weight: 0.7 }),
    e({ source: 'INT1_007', target: 'ODE_003', type: 'DERIVES', weight: 0.65 }),
    e({ source: 'INT1_002', target: 'INTM_001', type: 'SIMILAR', weight: 0.7 }),
    e({ source: 'INT1_009', target: 'SER_002', type: 'SIMILAR', weight: 0.75 }),
    e({ source: 'SER_005', target: 'DIFF1_011', type: 'SIMILAR', weight: 0.65 }),
    e({ source: 'INTM_007', target: 'INTM_010', type: 'DERIVES', weight: 0.8 }),
    e({ source: 'INTM_010', target: 'INTM_012', type: 'DERIVES', weight: 0.75 }),
    e({ source: 'DIFFM_008', target: 'DIFF1_013', type: 'SIMILAR', weight: 0.65 }),
    e({ source: 'VEC_002', target: 'DIFFM_004', type: 'DERIVES', weight: 0.55 }),
    e({ source: 'LIM_012', target: 'SER_001', type: 'SIMILAR', weight: 0.55 }),
    e({ source: 'DIFF1_010', target: 'INT1_016', type: 'SIMILAR', weight: 0.6 }),
    e({ source: 'LIM_016', target: 'SER_002', type: 'SIMILAR', weight: 0.5 }),
    e({ source: 'INTM_012', target: 'ODE_005', type: 'SIMILAR', weight: 0.55 }),
  ],
}

export function buildCatalogIndex(catalog: TopicCatalog): CatalogIndex {
  const seen = new Set<string>()
  const nodes: TopicNode[] = []
  for (const node of catalog.nodes) {
    if (seen.has(node.id)) {
      if (import.meta.env.DEV) {
        console.warn(`[hmath] 忽略重复 node id: ${node.id}（已保留首条，避免白屏；请在图谱管理中清理）`)
      }
      continue
    }
    seen.add(node.id)
    nodes.push(node)
  }

  const byId = new Map<string, TopicNode>(nodes.map((n) => [n.id, n]))
  const children = new Map<string, TopicNode[]>()
  for (const node of nodes) {
    if (!node.parentId) continue
    const arr = children.get(node.parentId) ?? []
    arr.push(node)
    children.set(node.parentId, arr)
  }
  for (const [, arr] of children) {
    arr.sort((a, b) => a.label.localeCompare(b.label, 'zh-CN'))
  }

  const edges = catalog.edges.filter((e) => {
    if (byId.has(e.source) && byId.has(e.target)) return true
    if (import.meta.env.DEV) {
      console.warn(`[hmath] 丢弃边（端点不存在）: ${e.source} —${e.type}→ ${e.target}`)
    }
    return false
  })

  const chapters = Array.from(new Set(nodes.map((n2) => n2.chapter))).sort((a, b) =>
    a.localeCompare(b, 'zh-CN'),
  )

  return {
    nodes,
    edges,
    byId,
    children,
    chapters,
  }
}

